server:
  port: 8081
spring:
  application:
    name: lootly
  datasource:
    url: jdbc:postgresql://localhost:5432/lootly_dev
    username: postgres
    password: postgres
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

http:
  logging:
    excluded-paths:
      - "/"
      - "/swagger"
      - "/actuator/**"
      - "/swagger-ui/**"
      - "/v3/api-docs/**"
      - "/health"
      - "/metrics/**"
      - "/internal/**"
      - "/management/**"